### ISSUE TITLE
Read blob to text

### ISSUE THREAD

**Issue by tbarlow12** [Azure/azure-storage-js#41]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
10.2.0-preview

### What's the Node.js/Browser version?
Browser

### What problem was encountered?
Ease of use. It seems like it should be a pretty common scenario to read text from blob. A lot of the other Azure storage SDKs have some kind of `readText` function that will read the text straight from blob into a string. Wondering if that's coming here as well.

### Have you found a mitigation/solution?
Yes. Currently using the workaround found in [example test file](https://github.com/Azure/azure-storage-js/blob/5274bd4272240c04485dc404926a78237c19296c/file/test/browser/highlevel.browser.test.ts) of `bodyToString` which calls `blobToString`. Seems like it could be something that fits better inside the SDK

**Comment by XiaoningLiu** [comment]
@tbarlow12  Thanks for reporting. 

In this SDK, browser download methods will return a Blob.  A Blob is a Browser native type represents a file-like object of immutable, raw data, which can be read to a binary buffer or a text. See

https://developer.mozilla.org/en-US/docs/Web/API/Blob

We will investigate what's best way to provide the flexibility to transfer a blob into text. For large blobs, simply read blob into text will sometimes "stuck" browser tab because of lacking of enough memory.

I'm kind of favor of let SDK developers do the job, as they know the source blob better. However, it's kind of not "user-friendly" to do a transfer as samples provided in "https://developer.mozilla.org/en-US/docs/Web/API/Blob".

**Comment by vinjiang** [comment]
Feel free to let us know if you need further assistance.
