### ISSUE TITLE
Samples should work with copy/paste

### ISSUE THREAD

**Issue by bterlson** [Azure/azure-storage-js#9]
The hero sample in README.md includes top-level await and doesn't import anything. It should include the imports. It should also include an `async function main`, a common pattern in samples.

Under the samples directory, the examples seem to assume they're running in the project, and not as an external dependency.

**Comment by XiaoningLiu** [comment]
You're right. The current sample in README.md demos usage pattern for common used APIs, but not a complete one. Will update it in next release.

I'm also guessing whether it's a good way to put a sample in readme.md, because it's out of testing, we may forget to updating the sample when API changes, just like another issue about headers you created.

**Comment by XiaoningLiu** [comment]
Resolved in release 10.1.0-preview, thanks!
